/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class InterfazJuego extends javax.swing.JFrame {

    /**
     * Creates new form InterfazJuego
     */
    public InterfazJuego() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Juego");
        this.getContentPane().setBackground(getBackground());
    }

    Tienda tienda = new Tienda();
    private int posicionActual;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        NombreMascota1 = new javax.swing.JLabel();
        NombreMascota2 = new javax.swing.JLabel();
        NombreMascota3 = new javax.swing.JLabel();
        NombreMascota4 = new javax.swing.JLabel();
        NombreMascota5 = new javax.swing.JLabel();
        NombreMascota6 = new javax.swing.JLabel();
        NombreMascota7 = new javax.swing.JLabel();
        NombreMascota8 = new javax.swing.JLabel();
        NombreMascota9 = new javax.swing.JLabel();
        NombreMascota10 = new javax.swing.JLabel();
        BotonMascota1 = new javax.swing.JButton();
        BotonMascota2 = new javax.swing.JButton();
        BotonMascota3 = new javax.swing.JButton();
        BotonMascota4 = new javax.swing.JButton();
        BotonMascota5 = new javax.swing.JButton();
        BotonMascota6 = new javax.swing.JButton();
        BotonMascota7 = new javax.swing.JButton();
        BotonMascota8 = new javax.swing.JButton();
        BotonMascota9 = new javax.swing.JButton();
        BotonMascota10 = new javax.swing.JButton();
        imagenPokemon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelNivel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        BotonLimpiar = new javax.swing.JButton();
        BotonAlimentar1 = new javax.swing.JButton();
        BotonPasear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelEnfermedades = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelLimpiar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelMostrarHambre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelPasear = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelEfecto = new javax.swing.JLabel();
        BotonRevivir = new javax.swing.JButton();
        labelAnimalARevivir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuTienda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        MenuAcercaDe = new javax.swing.JMenu();
        MenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Mis Pokemons");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NombreMascota1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota1.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota2.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota3.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota4.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota5.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota6.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota7.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota8.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota8.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota9.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota9.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NombreMascota10.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 14)); // NOI18N
        NombreMascota10.setForeground(new java.awt.Color(0, 0, 0));
        NombreMascota10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BotonMascota1.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\No0.png")); // NOI18N
        BotonMascota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota1ActionPerformed(evt);
            }
        });

        BotonMascota2.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\1.png")); // NOI18N
        BotonMascota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota2ActionPerformed(evt);
            }
        });

        BotonMascota3.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\2.png")); // NOI18N
        BotonMascota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota3ActionPerformed(evt);
            }
        });

        BotonMascota4.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\3.png")); // NOI18N
        BotonMascota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota4ActionPerformed(evt);
            }
        });

        BotonMascota5.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\4.png")); // NOI18N
        BotonMascota5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota5ActionPerformed(evt);
            }
        });

        BotonMascota6.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\6.png")); // NOI18N
        BotonMascota6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota6ActionPerformed(evt);
            }
        });

        BotonMascota7.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\7.png")); // NOI18N
        BotonMascota7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota7ActionPerformed(evt);
            }
        });

        BotonMascota8.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\8.png")); // NOI18N
        BotonMascota8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota8ActionPerformed(evt);
            }
        });

        BotonMascota9.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\5.png")); // NOI18N
        BotonMascota9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota9ActionPerformed(evt);
            }
        });

        BotonMascota10.setIcon(new javax.swing.ImageIcon("C:\\Users\\julio\\Documents\\Tareas universidad tercer semestre\\intro a la progra\\Practica2\\src\\main\\java\\com\\mycompany\\practica2\\imagenes\\9.png")); // NOI18N
        BotonMascota10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMascota10ActionPerformed(evt);
            }
        });

        imagenPokemon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hambre");

        LabelNivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nivel");

        LabelNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonAlimentar1.setText("Curar");

        BotonPasear.setText("Pasear");
        BotonPasear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPasearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apodo");

        labelEnfermedades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enfermedades");

        labelLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Limpiarme");

        labelMostrarHambre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pasearme");

        labelPasear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre");

        LabelTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Efecto");

        labelEfecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotonRevivir.setText("Revivir");
        BotonRevivir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRevivirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Animal a revivir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NombreMascota6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(BotonMascota9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(BotonMascota6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonMascota7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(BotonRevivir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NombreMascota7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(NombreMascota8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(NombreMascota9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelAnimalARevivir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(NombreMascota10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreMascota2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(BotonMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(NombreMascota3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotonMascota3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NombreMascota4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NombreMascota5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonMascota8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonMascota10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonMascota4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonMascota5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LabelNivel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                            .addComponent(LabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelEfecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMostrarHambre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPasear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonAlimentar1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonPasear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 122, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonMascota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonMascota4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonMascota5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonMascota2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonMascota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreMascota4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreMascota1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreMascota2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreMascota3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreMascota5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(labelEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelMostrarHambre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(LabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(labelPasear, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotonMascota6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonMascota9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonMascota7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonMascota8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonMascota10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreMascota7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreMascota9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreMascota10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NombreMascota6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NombreMascota8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAlimentar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonPasear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAnimalARevivir)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BotonRevivir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenuBar1.setBackground(new java.awt.Color(138, 196, 204));
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(307, 35));

        MenuTienda.setBackground(new java.awt.Color(139, 196, 204));
        MenuTienda.setForeground(new java.awt.Color(0, 0, 0));
        MenuTienda.setText("Tienda");
        MenuTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTiendaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Abrir tienda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuTienda.add(jMenuItem1);

        jMenuBar1.add(MenuTienda);

        MenuReportes.setBackground(new java.awt.Color(139, 196, 204));
        MenuReportes.setForeground(new java.awt.Color(0, 0, 0));
        MenuReportes.setText("Reportes");
        jMenuBar1.add(MenuReportes);

        MenuAcercaDe.setBackground(new java.awt.Color(139, 196, 204));
        MenuAcercaDe.setForeground(new java.awt.Color(0, 0, 0));
        MenuAcercaDe.setText("Acerca de");
        jMenuBar1.add(MenuAcercaDe);

        MenuAyuda.setBackground(new java.awt.Color(138, 196, 204));
        MenuAyuda.setForeground(new java.awt.Color(0, 0, 0));
        MenuAyuda.setText("Ayuda");
        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTiendaActionPerformed

    }//GEN-LAST:event_MenuTiendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tienda tienda = new Tienda();
        tienda.setVisible(true);
        tienda.getLabelOro().setText(tienda.getDineroString());
        tienda.getLabelOro2().setText(tienda.getDineroString());
        tienda.getLabelOro1().setText(tienda.getDineroString());

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BotonMascota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota1ActionPerformed
        try {
            NombreMascota1.setText(tienda.getPokemones(0).getNombre());
            mostrarPokemon(0);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota1ActionPerformed

    private void BotonMascota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota2ActionPerformed
        try {
            NombreMascota2.setText(tienda.getPokemones(1).getNombre());
            mostrarPokemon(1);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota2ActionPerformed

    private void BotonMascota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota3ActionPerformed
        try {
            NombreMascota3.setText(tienda.getPokemones(2).getNombre());
            mostrarPokemon(2);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota3ActionPerformed

    private void BotonMascota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota4ActionPerformed
        try {
            NombreMascota4.setText(tienda.getPokemones(3).getNombre());
            mostrarPokemon(3);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota4ActionPerformed

    private void BotonMascota5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota5ActionPerformed
        try {
            NombreMascota5.setText(tienda.getPokemones(4).getNombre());
            mostrarPokemon(4);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota5ActionPerformed

    private void BotonMascota9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota9ActionPerformed
        try {
            NombreMascota6.setText(tienda.getPokemones(5).getNombre());
            mostrarPokemon(5);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota9ActionPerformed

    private void BotonMascota6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota6ActionPerformed
        try {
            NombreMascota7.setText(tienda.getPokemones(6).getNombre());
            mostrarPokemon(6);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota6ActionPerformed

    private void BotonMascota7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota7ActionPerformed
        try {
            NombreMascota8.setText(tienda.getPokemones(7).getNombre());
            mostrarPokemon(7);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota7ActionPerformed

    private void BotonMascota8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota8ActionPerformed
        try {
            NombreMascota9.setText(tienda.getPokemones(8).getNombre());
            mostrarPokemon(8);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota8ActionPerformed

    private void BotonMascota10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMascota10ActionPerformed
        try {
            NombreMascota10.setText(tienda.getPokemones(9).getNombre());
            mostrarPokemon(9);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay un pokemon en ese lugar");
        }
    }//GEN-LAST:event_BotonMascota10ActionPerformed

    private void BotonRevivirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRevivirActionPerformed
        try {
            int pokemonARevivir = Integer.parseInt(labelAnimalARevivir.getText());
            if (!tienda.getPokemones(pokemonARevivir).isVivo()) {
                int precio = (5 * tienda.getPokemones(pokemonARevivir).getNivel()) + 10;
                tienda.setDinero(precio);
                tienda.getPokemones(pokemonARevivir).cambiarEstado(true);
                JOptionPane.showMessageDialog(this, tienda.getPokemones(pokemonARevivir).getNombre() + " ha revivido");
                tienda.getPokemones(pokemonARevivir).resume();
                tienda.getPokemones(pokemonARevivir).reiniciarHambre();
            } else {
                JOptionPane.showMessageDialog(this, "Este pokemon esta vivo");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay ningun pokemon en esta posicion");
        }
    }//GEN-LAST:event_BotonRevivirActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        tienda.getPokemones(this.posicionActual).limpiar();
        JOptionPane.showMessageDialog(this, "Haz limpiado a " + tienda.getPokemones(this.posicionActual).getNombre());
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonPasearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPasearActionPerformed
        menuinicio juego = new menuinicio();
        juego.setVisible(true);
        tienda.aumentarDinero();
    }//GEN-LAST:event_BotonPasearActionPerformed

    private void mostrarPokemon(int noMascota) {
        if (tienda.pokemones[noMascota].isVivo()) {
            LabelNombre.setText(tienda.getPokemones(noMascota).getNombre());
            LabelNivel.setText(tienda.getPokemones(noMascota).getNivelString());
            LabelTipo.setText(tienda.getPokemones(noMascota).getTipo());
            imagenPokemon.setIcon(new ImageIcon(tienda.getPokemones(noMascota).getImagen()));
            labelMostrarHambre.setText(tienda.getPokemones(noMascota).getHambreString());
            labelEfecto.setText(tienda.getPokemones(noMascota).getEfectoComida());
            labelEnfermedades.setText(tienda.getPokemones(noMascota).getEnfermedadString());
            labelLimpiar.setText(tienda.getPokemones(noMascota).getLimpiar());
            labelPasear.setText(tienda.getPokemones(noMascota).getPasear());
            this.posicionActual = noMascota;
        } else {
            imagenPokemon.setIcon(new ImageIcon("C:/Users/julio/Documents/Tareas universidad tercer semestre/intro a la progra/Practica2/src/main/java/com/mycompany/practica2/imagenes/muerto.png"));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlimentar1;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonMascota1;
    private javax.swing.JButton BotonMascota10;
    private javax.swing.JButton BotonMascota2;
    private javax.swing.JButton BotonMascota3;
    private javax.swing.JButton BotonMascota4;
    private javax.swing.JButton BotonMascota5;
    private javax.swing.JButton BotonMascota6;
    private javax.swing.JButton BotonMascota7;
    private javax.swing.JButton BotonMascota8;
    private javax.swing.JButton BotonMascota9;
    private javax.swing.JButton BotonPasear;
    private javax.swing.JButton BotonRevivir;
    private javax.swing.JLabel LabelNivel;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JMenu MenuAcercaDe;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuTienda;
    private javax.swing.JLabel NombreMascota1;
    private javax.swing.JLabel NombreMascota10;
    private javax.swing.JLabel NombreMascota2;
    private javax.swing.JLabel NombreMascota3;
    private javax.swing.JLabel NombreMascota4;
    private javax.swing.JLabel NombreMascota5;
    private javax.swing.JLabel NombreMascota6;
    private javax.swing.JLabel NombreMascota7;
    private javax.swing.JLabel NombreMascota8;
    private javax.swing.JLabel NombreMascota9;
    private javax.swing.JLabel imagenPokemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField labelAnimalARevivir;
    private javax.swing.JLabel labelEfecto;
    private javax.swing.JLabel labelEnfermedades;
    private javax.swing.JLabel labelLimpiar;
    private javax.swing.JLabel labelMostrarHambre;
    private javax.swing.JLabel labelPasear;
    // End of variables declaration//GEN-END:variables
}
